name:                gswitch
version:             0.1.0.0
homepage:            https://github.com/miuirussia/gswitch#readme
license:             MIT
author:              Kirill Kuznetsov
maintainer:          kirill.desirehd@gmail.com
copyright:           (C) 2020 Kirill Kuznetsov
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - deriving-aeson
  - envparse
  - http-client
  - http-client-tls
  - lens
  - optparse-applicative
  - servant
  - servant-client
  - servant-flatten
  - text

default-extensions:
  - DeriveGeneric
  - DerivingVia
  - NamedFieldPuns
  - OverloadedStrings
  - RecordWildCards

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -funbox-strict-fields

executables:
  gswitch:
    source-dirs:
      - app
    main:
      Main.hs
    dependencies:
      - gswitch

library:
  source-dirs:
    - src
