#!/usr/bin/env bash
# vim: set ft=bash
# adapted from https://github.com/cachix/install-nix-action/blob/master/src/main.ts

set -euo pipefail

sudo mkdir -p /etc/nix

# Workaround segfault: https://github.com/NixOS/nix/issues/2733
sudo sh -c 'echo "http2 = false" >> /etc/nix/nix.conf'


if [[ $OSTYPE =~ darwin ]]; then
    echo "Installing on Darwin"
    sudo sh -c "echo \"nix\t/opt/nix\" >> /etc/synthetic.conf"
    sudo sh -c "mkdir -m 0755 /opt/nix && chown runner /opt/nix"
    /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B
    sudo sh -c "echo 'Defaults env_keep += NIX_IGNORE_SYMLINK_STORE' >> /etc/sudoers"
    echo "::set-env name=NIX_IGNORE_SYMLINK_STORE::1"
    export NIX_IGNORE_SYMLINK_STORE=1
    sudo launchctl setenv NIX_IGNORE_SYMLINK_STORE 1

    cert_file=~/.nix-profile/etc/ssl/certs/ca-bundle.crt
    echo "::set-env name=NIX_SSL_CERT_FILE::$cert_file"
    export NIX_SSL_CERT_FILE=$cert_file
    sudo launchctl setenv NIX_SSL_CERT_FILE "$cert_file"
fi

curl https://nixos.org/nix/install | sh

sudo sh -c 'echo "substituters = https://cache.nixos.org https://kdevlab.cachix.org https://hercules-ci.cachix.org https://iohk.cachix.org" > /etc/nix/nix.conf'
sudo sh -c 'echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hercules-ci.cachix.org-1:ZZeDl9Va+xe9j+KqdzoBZMFJHVQ42Uu/c/1/KMC5Lw0= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= kdevlab.cachix.org-1:9RZJXb65g6iVS5GVk+jCMcZDidyJMzFqsAn5yUBmB8w=" >> /etc/nix/nix.conf'

echo "::add-path::/nix/var/nix/profiles/per-user/runner/profile/bin"
echo "::add-path::/nix/var/nix/profiles/default/bin"
